# This is a config for E2B sandbox template.
# You can use template ID (r63p4almt0cedqhjrqek) or template name (renaut-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("renaut-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("renaut-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('renaut-nextjs-test2')

team_id = "092643d7-d103-404e-b68e-e2db10e2f064"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "renaut-nextjs-test2"
template_id = "r63p4almt0cedqhjrqek"
